spring:
  application:
    group: localhost
    name: spring-reactive-kotlin-gradle
  data:
    mongodb:
      enabled: true
      auto-index-creation: true
      uri: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false
      database: products_db
      authentication-database: products_db
      repositories:
        type: reactive
  cloud:
    stream:
      kafka:
        binders:
          headers: PARTITION_ID
      bindings:
        myConsumerConfChannelIn:
          destination: topic-of-business-v1
          contentType: application/json
          group: ${spring.application.name}
          consumer:
            partitioned: true
        myConsumerConfChannelOut:
          destination: topic-of-business-v2
          contentType: application/json
          group: ${spring.application.name}
          producer:
            partitionKeyExpression: headers['PARTITION_ID']
endpoints:
  customer-assets:
    url: http://assets-localhost/api/v1
  costumer:
    data:
      url: http://customer-localhost/api/v1
  acquisition:
    orders:
      url: http://orders-localhost/api/v1